<?php

/**
 * @file
 * Contains phantomjs_tester.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function phantomjs_tester_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the phantomjs_tester module.
    case 'help.page.phantomjs_tester':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
